basePath: /
host: localhost:8080
info:
  contact: {}
  description: API for creating, listing, searching, and filtering articles.
  title: Article Service API
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
